### ISSUE TITLE
database setup

### ISSUE THREAD

**Issue by Seerden** [Seerden/dash#1]
# Description

Set up a skeleton for the client.

# Background

Set up the database.

# Implementation notes

* I want a better way of doing migrations — keeping a list of \[number\]-\[description\].sql files works, but we need a way to check which files have been run already. could be done in a database table, or we store it persistently in redis or on file.

# To-do

- [X] set up a postgres container for the 'test' and the 'dev' (= prod when deployed) databases.
- [X] use a container in a docker-compose setup.
- [ ] make sure to add the list of required environment variables to a README somewhere — for now, I just put the .env in my Google password manager, so I know where to find it if needed.
- [ ] set up a way to handle creation of tables and seeding, and migrations
  - [ ] note: this needs to be separate for test and "real" database — even though we want the test database to functionally be a mirror of the real one (with other data), they're not intrinsically linked. All scripts need to be run individually on each db.
