### ISSUE TITLE
server setup

### ISSUE THREAD

**Issue by Seerden** [Seerden/dash#2]
# Description

Look through `track` and see if there are any things missing from there that we need for the backend. Message queues for example, I used those in the first version of dash to set up cronjobs for fetching from Polygon.io.

# Background

Setting up the application. Want to get the structure of the repo in place before we do any programming at all.

# Implementation notes

Needs to be containerized.

I think I would like to try some new tech for this.

- [X] if on node, maybe try trpc
- [ ] ~~if not on node (choose Go?), everything is new and I don't even know where to start and what I'll need~~

# To-do

- [X] npm init
- [X] connections to redis and the database
- [ ] sentry setup (later, see [DAS-11](https://linear.app/seerden/issue/DAS-11/set-up-sentry))
- [X] typescript config? — got this from track blueprint
- [ ] router setup — do we use express again, or try something else? — using trpc ([DAS-14](https://linear.app/seerden/issue/DAS-14/set-up-trpc))
